### ISSUE TITLE
Not Working anymore

### ISSUE THREAD

**Issue by neryreginato** [nikitakatchik/smarttv-twitch#113]
Is it just me, or this week the app stop working? Every channel I try to watch I receive the error message: "Unable to retrieve access token".

Version: 3.6

**Comment by rafaelfcabral** [comment]
Same here

**Comment by Ottha** [comment]
Please Yoda your Version. For details check issue #111 in the closes section.
Link: https://github.com/nikitakatchik/smarttv-twitch/issues/111

**Comment by xt449** [comment]
Yup doesn't work anymore even with the latest version

**Comment by sqbi87** [comment]
But how do I update it?

**Comment by henriquelbsouza** [comment]
Hi @sqbi87 I did an updated yesterday. You can follow the instructions on README file, it worked for me with SammyWidgets... It is pretty simple... Here is the steps I did:

1- Download Sammy Widgets v1.1 (I get it from google, it came with a few widgets already that I just deleted.) (Also you will need to extract it since you need to put the twitch zip into the widgets folder)
2- Login as developer (there are 3 videos in the README file for each model/version of TVs, mine was H series)
3- Inside SAMSUNG APPS In ANY APPLICATION hold the "ENTER" button on your controller to open the menu (it is for H series) and configure your IP address for your computer (again, the videos can show you better)
4- Do the same as before to open the menu and after that just sync apps (last option on H series)

Twitch app should be installed in the new version now (I would recommend deleting the previously one to make sure it updated) 

Another thing... The zip file cannot have a folder with the files, it needs to have ALL the files and subfolders in the root folder... (I think that if you download the release zip file should be fine)

Good luck :)

**Comment by sqbi87** [comment]
Thanks I'll try to do as you said :)

**Comment by neryreginato** [comment]
Thank you @henriquelbsouza and @nikitakatchik !! Twitch app for samsung is working again! Thank you very much.

**Comment by bibine222** [comment]
Thank you guys. Enjoying twitch on tv with your app.

**Comment by besasdev** [comment]
@henriquelbsouza @sqbi87 @nikitakatchik I downloaded sammy widgets and did all the steps but it doesn't work for me. When I try to download from webserver nothing happens. I put the IP in chrome but it only downloads a 9kb file with nothing in it. Please help.
